### ISSUE TITLE
Project doesn't work with Bosh v2

### ISSUE THREAD

**Issue by sasadangelo** [georgethebeatle/simple-bosh-release#6]
Hi,

Tried your tutorial on Bosh v2 and I noticed commands you documented was for Bosh v1 and didn't work with my Bosh lite v2. I tried to deploy Apache HTTP server 2.4.39 and commands changed a bit because HTTP server requires some libraries as a prerequisite. Moreover, I used Ubuntu 16 xenial as a stem cell. I forked your code and modify it in order to support my requirements. I modified documentation too to reflects these changes. Check out the code here https://github.com/sasadangelo/simple-bosh-release you can use it as you prefer.

**Comment by hsiliev** [comment]
Hey @sasadangelo,

Do you care to create a PR with your changes? It would be more than welcome

**Comment by sasadangelo** [comment]
Hi,

I can do it this evening (CEST time). Please review it, I am a newbie with bosh and I don't want to make a mistake. However, I tested it on my Mac and it worked. You can take whatever piece you think it is ok for you. I used your project to experiment, step by step, with bosh deployment.

**Comment by sasadangelo** [comment]
Hey @hsiliev,

Here the PR, feel free to integrate whatever you think it is ok for you.
https://github.com/georgethebeatle/simple-bosh-release/pull/7

**Comment by sasadangelo** [comment]
Hey @hsiliev,

Tried again with new PR https://github.com/georgethebeatle/simple-bosh-release/pull/8 but same README.md conflict. I started coding from the last commit and then added my two commits. Push didn't notice any problem. In PR I have a button to resolve conflicts but clicking on it hangs. Probably only people having writing access have this issue.

To be honest I do not know how to solve the issue. Probably you can git pull your official project, put my two commits on top. 

If you have indications for me I'll be happy to follow them.

**Comment by sasadangelo** [comment]
Hi all,

I created a new PR to compile Apache HTTP server 2.4.39 completely from source code https://github.com/georgethebeatle/simple-bosh-release/pull/10. I tested it on my Mac. For any question, let me know.

**Comment by sasadangelo** [comment]
Hey @georgethebeatle,

I noticed you merged PR #10. Thank you. 
Regarding network warnings to move in cloud-config I'll do it ASAP.

**Comment by georgethebeatle** [comment]
Looks like all PRs have been merged, so closing. Thank you @sasadangelo
